# Generated by Django 4.2.7 on 2025-11-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('estimated_duration', models.FloatField(default=1.0, help_text='Estimated duration in hours')),
                ('complexity', models.IntegerField(default=1, help_text='Complexity score 1-10')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='tasks.task')),
            ],
            options={
                'ordering': ['-priority', 'deadline'],
                'indexes': [models.Index(fields=['status', 'priority'], name='tasks_task_status_01b536_idx'), models.Index(fields=['deadline'], name='tasks_task_deadlin_736196_idx')],
            },
        ),
    ]
